### ISSUE TITLE
Is it possible to get frame information?

### ISSUE THREAD

**Issue by AjitsinghKamal** [ksvc/react-native-video-player#10]
I am using this to play a rtmp stream and want to get the information from each frame. Is it possible to extract this info or listen for any event in the stream

**Comment by dengchu817** [comment]
Do you want to know the width and height of each frame?
The propTypes`onLoad` can listen for width and height and duration of the stream

**Comment by AjitsinghKamal** [comment]
Thanks, but that's not entirely what I am looking for. Basically I want to sync some part of my app with the stream that is being played. The will be carrying cuepoints with it in each frame for the same reason. I am trying to extract these cuepoints and just wondering if it is possible to do so

**Comment by dengchu817** [comment]
This functionality was not present

**Comment by AjitsinghKamal** [comment]
Cool. Since the feature is not present we should close this issue
