### ISSUE TITLE
Native component for "RCTKSYVideo" does not exist

### ISSUE THREAD

**Issue by nguyenanhthai** [ksvc/react-native-video-player#19]
I have followed installation instructions in iOS, but can not success. 
When I tried a RTMP link, I get this error: 
`Native component for "RCTKSYVideo" does not exist`
Any advice for me?

**Comment by canyara** [comment]
you need to change "react-native-ksyvideo.podspec".

`-  s.source_files  = "ios/*.{h,m}"
+  s.source_files  = "ios/RCTKSYVideo/*.{h,m}"`

**Comment by nguyenanhthai** [comment]
Thanks. I have resolved by run 
`pod update`

**Comment by NomadGraphix** [comment]
Can we create a pull request to fix this?
