### ISSUE TITLE
Binary XML file line #6: Binary XML file line #6: Error inflating class <unknown>  Binary XML file line #6: Error inflating class <unknown>  null  

### ISSUE THREAD

**Issue by sohoorc** [ksvc/react-native-video-player#35]
在使用过程中出现这个错误：

Binary XML file line #6: Binary XML file line #6: Error inflating class <unknown>

Binary XML file line #6: Error inflating class <unknown>

null

No implementation found for void com.ksyun.media.player.KSYMediaPlayer.native_init() (tried Java_com_ksyun_media_player_KSYMediaPlayer_native_1init and Java_com_ksyun_media_player_KSYMediaPlayer_native_1init__)

如图：
![image](https://user-images.githubusercontent.com/22408518/48053005-77975680-e1e4-11e8-93d2-7e381cc828ef.png)

版本信息：
![qq20181106-165412](https://user-images.githubusercontent.com/22408518/48053057-a1e91400-e1e4-11e8-846d-66909123e7cf.png)

![image](https://user-images.githubusercontent.com/22408518/48053088-b6c5a780-e1e4-11e8-90a3-a5112d0608a5.png)

**Comment by sohoorc** [comment]
该问题出现在 Android studio 的x86模拟器下，真机上没发现。

**Comment by nvojnovic** [comment]
This is the reason https://github.com/ksvc/react-native-video-player/issues/28#issuecomment-430685464
