### ISSUE TITLE
release mode error ——library not found for -lRCTKSYVideo

### ISSUE THREAD

**Issue by sohoorc** [ksvc/react-native-video-player#37]
IOS下使用release模式运行， 提示：
ld: library not found for -lRCTKSYVideo
clang: error: linker command failed with exit code 1 (use -v to see invocation)
![image](https://user-images.githubusercontent.com/22408518/48819009-da622380-ed88-11e8-909d-6af3ec57f870.png)

android打包release模式 
![image](https://user-images.githubusercontent.com/22408518/48819050-f82f8880-ed88-11e8-9a63-4ad42a328028.png)

ios 和 android使用debug模式都是正常，该问题只出现在release模式下。请问是什么原因呢。

**Comment by yunuo-tech** [comment]
我也碰到这问题了，ios如何解决的？

**Comment by jamninetyfive** [comment]
@sohoorc 请问如何解决的？

**Comment by jamninetyfive** [comment]
#40  solve it in ios！
