### ISSUE TITLE
Execution failed for task ':react-native-ksyvideo:verifyReleaseResources'

### ISSUE THREAD

**Issue by jackhe16** [ksvc/react-native-video-player#38]
![image](https://user-images.githubusercontent.com/25236792/50571020-f9b58d00-0dd9-11e9-96e3-9450de1498ad.png)

ReactNative: 0.57
gradle-wrapper: gradle-4.4-all.zip
com.android.tools.build:gradle: 3.1.4
buildToolsVersion = "27.0.3"
minSdkVersion = 16
compileSdkVersion = 27
targetSdkVersion = 26
supportLibVersion = "27.1.1"

react-native run-android (is ok)
cd android && ./gradlew assembleRelease (can't work)

**Comment by hmaamoun** [comment]
Hello,

Any update on this. We are facing the same issue

**Comment by jackhe16** [comment]
Sorry, I am busy recently. I have tried the following.
1. Keep the compileSdkVersion and buildToolsVersion in node_modules/react-native-video-player/android/build.gradle consistent with those in the react-native project.
2. Finally I use the react-native-video-player library, although it can't be played in the emulator, but it's available in real devices by hardware decoding.

**Comment by omerdn1** [comment]
@jackhe16 
if I try to match the `compileSdkVersion` in `node_modules/react-native-video-player/android/build.gradle` with my react-native project I get this error:
`Error: Permission is only granted to system apps [ProtectedPermissions]` for the `<uses-permission android:name="android.permission.WRITE_SETTINGS"/>` permission.
any update on this issue?

**Comment by jackhe16** [comment]
It seems to be another problem, have you read this PermissionsAndroid doc page for Android 6.0 +?
